### ISSUE TITLE
another site where URL coversion fails

### ISSUE THREAD

**Issue by alexanderzatko** [rvnproject/DOIACCESS#12]
https://psycnet.apa.org/record/2010-02412-005

FF 67.0.4 on MacOS
using plugin version 1.04

**Comment by mde-pach** [comment]
There is a massive update coming with many case like yours fixed :)
Thank you again for contributing !

**Comment by mde-pach** [comment]
Now fix on FF, the chrome fix is coming (chrome webstore verifications)
